services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_php
    volumes:
      - ./html:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    depends_on:
      - database
    ports:
      - "${WORDPRESS_PORT}:9000"

  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi:/var/cache/nginx/fastcgi
    ports:
      - "80:80"
    depends_on:
      - wordpress

  database:
    image: mysql:8.0
    container_name: wordpress_mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADMIN_USER=${MYSQL_ADMIN_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - wordpress_woocommerce_mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: wordpress_redis
    platform: linux/arm64
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  k6:
    image: grafana/k6
    container_name: wordpress_k6
    volumes:
      - ./k6/scripts/stress_test.js:/scripts/stress_test.js:ro
      - ./k6/logs:/logs
    command: run /scripts/stress_test.js
    environment:
      - BASE_URL=http://nginx/
      # - BASE_URL=http://nginx/?post_type=product
    depends_on:
      - wordpress

  k6_elk:
    build:
      context: k6
      dockerfile: Dockerfile
    container_name: wordpress_k6_elk
    volumes:
      - ./k6/scripts/stress_test.js:/scripts/stress_test.js:ro
      - ./k6/logs:/logs
    # command: run /scripts/stress_test.js --summary-export=/logs/summary.json --out output-elasticsearch
    command: run /scripts/stress_test.js --summary-export=/logs/summary.json --out json=/logs/output.json
    environment:
      - BASE_URL=http://nginx/
      - K6_OUT=output-elasticsearch
      - K6_ELASTICSEARCH_USER=elastic
      - K6_ELASTICSEARCH_PASSWORD=pass
      - K6_ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - wordpress
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=pass
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=pass
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'

  grafana:
    image: grafana/grafana
    container_name: wordpress_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  wordpress_woocommerce_mysql_data:
  elasticsearch_data:
  kibana_data:
  prometheus_data:
  grafana_data:
