services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_php
    volumes:
      - ./html:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    depends_on:
      - database
    ports:
      - "${WORDPRESS_PORT}:9000"

  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - wordpress

  database:
    image: mysql:8.0
    container_name: wordpress_mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADMIN_USER=${MYSQL_ADMIN_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - wordpress_woocommerce_mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'

  k6:
    image: grafana/k6
    container_name: wordpress_k6
    ports:
      - "6565:6565"
    volumes:
      - ./k6:/scripts
    command: run /scripts/stress_test.js --address 0.0.0.0:6565 --out experimental-prometheus-rw
    environment:
      # - K6_PROMETHEUS_PUSH_GATEWAY_URL=http://prometheus:9091/metrics
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - BASE_URL=http://nginx/
    depends_on:
      - prometheus
      - wordpress

  grafana:
    image: grafana/grafana
    container_name: wordpress_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  wordpress_woocommerce_mysql_data:
  prometheus_data:
  grafana_data:
